version: '3.8'
services:
  frontend:
    build: ./dashboard
    environment:
      - PUBLIC_IP=${PUBLIC_IP}
    ports:
      - "8080:80"
    depends_on:
      - backend
  backend:
    build: ./backend
    environment:
      - PUBLIC_IP=${PUBLIC_IP}
      - MSAL_CLIENT_ID=${MSAL_CLIENT_ID}
      - MSAL_TENANT_ID=${MSAL_TENANT_ID}
    ports:
      - "3000:3000"
